#!/usr/bin/perl
use strict;
use Data::Dumper;

my $name;
my $ver;
my %patches;

my $prefix = $ARGV[0];
$prefix =~ s,/[^/]*$,,;
if ($prefix) {
    $prefix .= "/";
}

my $s = 0;
while (<>) {
    SWITCH: {
        if (/^\s*name\s*:\s*(.*)$/i) { $name = $1; last SWITCH; }
        if (/^\s*version\s*:\s*(.*)$/i) { $ver = $1; last SWITCH; }
        if (/^(#|)\s*patch(\d*)\s*:\s*(.*)$/i) {
            if ($1 eq "#") {
                $patches{$2}{'commented'} = 1;
            }
            $patches{$2}{'file'} = $3;
            last SWITCH;
        }
        if (/^\s*(%|#|#% )patch(\d*)[^:]+?\s*(.*)$/i) { 
            if ($1 ne "%") {
                $patches{$2}{'commented'} = 1;
            }
            $patches{$2}{'seq'} = $s++;
            $patches{$2}{'opts'} = $3;
            last SWITCH;
        }
    }
}

my @queue;
foreach my $n (keys(%patches)) {
    $patches{$n}{'file'} =~ s@%(name|{name})@$name@gi;
    $patches{$n}{'file'} =~ s@%(version|{version})@$ver@gi;
    $queue[$patches{$n}{'seq'}] = $n;
}

foreach my $n (@queue) {
    if (exists($patches{$n}{'commented'})) {
        print "# $patches{$n}{'opts'} < ${prefix}$patches{$n}{'file'}\n";
    } else {
        print "$patches{$n}{'opts'} < ${prefix}$patches{$n}{'file'}\n";
    }
}

